version: '3.8'

services:
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    restart: always

    # You need to create .env file in locoride/locoride-project directory and add the following environment variables
    environment:
      - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - NEXT_PUBLIC_GOOGLE_API_KEY=${NEXT_PUBLIC_GOOGLE_API_KEY}
      - NEXT_PUBLIC_CLERK_SIGN_IN_URL=${NEXT_PUBLIC_CLERK_SIGN_IN_URL}
      - NEXT_PUBLIC_CLERK_SIGN_UP_URL=${NEXT_PUBLIC_CLERK_SIGN_UP_URL}
      - NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL=${NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL}
      - NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL=${NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL}

    depends_on:
      - backend
      - mysql
      - postgres

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    restart: always
    depends_on:
      - mysql
      - postgres

  mysql:
    image: mysql:5.7
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: adminx
      MYSQL_DATABASE: locoride
      MYSQL_USER: adminx
      MYSQL_PASSWORD: adminx

  postgres:
    image: postgres:13
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: locoride
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    logging:
      options:
        max-size: 10m
        max-file: '3'
    volumes:
      - ./db-data/postgres:/var/lib/postgresql/data
      # - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8081:80'
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: adminx

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - '8082:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: adminx@adminx.com
      PGADMIN_DEFAULT_PASSWORD: adminx
    depends_on:
      - postgres
